variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MKDOCS_VERSION: '1.2.1'
  MATERIAL_VERSION: '7.1.10'
  I18NSTATIC_VERSION: '0.17'

stages:
  - pages

pages:
  image: python:3.8-alpine
  stage: pages
  script:
    - apk add --no-cache git subversion
    - pip install --upgrade pip setuptools wheel
    - pip install mkdocs==${MKDOCS_VERSION} mkdocs-material==${MATERIAL_VERSION} mkdocs-static-i18n==${I18NSTATIC_VERSION}
    - if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi;
    - mkdocs build -d public
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
