# setup doc: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
#
site_name: CMS ETL Readout Board
site_url: https://apollo-lhc.gitlab.io/mkdocs
site_dir: public
theme:
  name: material
    #logo: './images/apollo.png'
    #favicon: './images/apollo.png'
  #favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    primary: 'darkgreen'
    accent: 'blue'
