# setup doc: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
#
site_name: CMS ETL Readout Board
site_url: http://etl-rb.web.cern.ch/
site_dir: public
theme:
  name: material
  logo: './images/cms_logo.jpeg'
  favicon: './images/cms_logo.jpeg'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    primary: 'teal'
    accent: 'blue'
